### PR TITLE
Added proposal for passenger/services.pax.customercommunication

### PR DESCRIPTION
**Pull request by andkrdfds**

### CODE REVIEW

**Comment by pywellj** [comment]
Ferry have a similar component to deal with sending out emails using Iterable.

Is it worth seeing if we have some common functionality here that can be elevated to something enterprise level?

**Comment by martinosk** [comment]
Yes, it could probably make sense that we have a common abstraction on top of iterable, like you mention @pywellj 
It sounds to me like this particular component is more about compiling the content for passenger emails and knowing when to send it, is that correct @andkrdfds ?  I guess the big question is, how much of this component is (passenger) domain specific and how much is generic/technical (Iterable integration) and could it make sense to seperate the two?

**Comment by andkrdfds** [comment]
@martinosk Yes that is correct - it is mostly about compiling data and knowing when to send. I guess the actual integration with Iterable will be minimal when is comes to it, so maybe we won't gain that much by separating it (for now anyways).

**Comment by andkrdfds** [comment]
Btw @pywellj where can I see the existing component you mentioned?

**Comment by pywellj** [comment]
> Btw @pywellj where can I see the existing component you mentioned?

I'm pretty sure that it's this one;

https://github.com/dfds/component-rfc/blob/master/freight/notification.md

Based on what I know about it, you essentially post a campaign Id and a data payload to it and it'll do the relevant mappings to Iterable.

**Comment by cbrig** [comment]
Open API spec can be found here: [](https://notification-component-test.freight.np.dfds.cloud/swagger/index.html )

**Comment by martinosk** [comment]
@andkrdfds could you update this with capability info and a few lines about the API? Then I will merge the RFC.

**Pull request merged**
